### PR TITLE
Timestamp tags

### PR DESCRIPTION
**Pull request by traels**
My deploy step told me that there were no tags. After debugging I found that the regex in `try_parse` filtered my tags out.

This should work just the same, without the regex.

Also setup very basic tests.

### CODE REVIEW

**Comment by camertron** [comment]
Hmm, that's interesting. What do you mean by "filtered my tags out"? Did you run `rake kuby:build`? If so, it should have tagged the image with a valid timestamp tag, which should have been discovered during `rake kuby:deploy`. What tags do you see for your image when running `docker images`?

**Comment by traels** [comment]
I went through build, worked as it should. 
Got a tag 20201008132354.
On deploy I got no tags error. I went splunking, and after removing the regex it worked. 

Sendt fra min iPad

**Comment by camertron** [comment]
Looks like there are several issues at play here. First of all, that timestamp, `20201008132354 `, doesn't look quite right. It should be `<year><month><day>`, but yours looks to be `<year><day><month>`. I have no idea how that happened, unless your computer thinks it's October for some reason?

The second issue is that there's a bug in the regex. It should be:

```ruby
/\A20[\d]{2}(?:0[1-9]|10|11|12)(?:0[1-9]|1[1-9]|2[1-9]|3[01])\z/
```

**Comment by camertron** [comment]
I updated the regex and published v0.7.0.

I really appreciate your willingness to dive in and submit a PR @traels. I'm going to close this for now, but please feel free to submit another PR introducing your test changes. If you do so, please use RSpec though, I'm not a big fan of minitest.

**Pull request closed without merging**
